### ISSUE TITLE
add: app icon

### ISSUE THREAD

**Issue by shriram-alagarasan** [IEEE-VIT/Xpendi#15]
add the app icon to xc.assests

**Comment by aswinikalyan30** [comment]
Can I work on this?

**Comment by aaryankotharii** [comment]
Hi @aswinikalyan30, sure! thank you for your interest in working on this issue. Feel free to design the app icon as you like!
Assigned.

**Comment by aswinikalyan30** [comment]
Hey! Is there any naming procedure and specific format for the icon?

**Comment by aaryankotharii** [comment]
> Hey! Is there any naming procedure and specific format for the icon?

nope, anything works!

**Comment by aswinikalyan30** [comment]
Hey, is the PR counted if it's done after the 8hr window or not?
