### ISSUE TITLE
swipe to delete

### ISSUE THREAD

**Issue by shriram-alagarasan** [IEEE-VIT/Xpendi#7]
implement swipe to delete feature to delete the balance value

**Comment by K4stor** [comment]
I'd like to work on that

**Comment by aaryankotharii** [comment]
Hi @K4stor, thank you for your interest in working on this issue!
Assigned.

**Comment by K4stor** [comment]
Hello @aaryankotharii  I can't build the project, it says ContenView.swift not found

**Comment by ananya190** [comment]
hi @K4stor there was an issue with the files that we resolved a few days ago. Try pulling from main again. If that doesn't work, let us know.
